- Syntax error SMCEngineAction() not found #13 - Added keyword ref-name to retrieve reference by name - Added keyword element-name to retrieve element by name - Fixed backward compatibility issues - Added generic network elements needed for engine creation - Fixed backward compatibility issues - Reworked the way to obtain reference from an element name - Used lookup ansible pluggin instead of manually update yaml node - Added 2 custom lookup pluggins: smc-reference and smc-element - Added variable to choose log folder: "log_folder" - Fixed backward compatibility SWP -> SWI - generic_element: added a yaml layer to define smc-reference - Use argparse library to provide api parameters in command line - Alias_facts: _remove_values_conditions TypeError - Fixed checkstyle for import and payload - Erreur:'ForcepointBGPElement' object has no attribute 'check_mode' - Module firewall_rule.py: RuntimeError: dictionary changed size during iteration